# Numpy

In [1]:
#código comparando a velocidade de excecucao do numpy com os tipos builtins do python
import numpy as np
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [2]:
%timeit my_arr2 = my_arr * 2

472 μs ± 2.48 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [3]:
%timeit my_list2 = [x * 2 for x in my_list]

58.3 ms ± 1.11 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
list1 = [0,1,2,3,4]
arr1d = np.array(list1)
# principal diferença entre list e array
print(arr1d + 2)
print(list1 + 2)  # erro

[2 3 4 5 6]


TypeError: can only concatenate list (not "int") to list

In [5]:
arr1d

array([0, 1, 2, 3, 4])

In [ ]:
type(arr1d)

In [6]:
x = [1,2,3,4.5,5.7]
print('--------- lists ----------\n')
print(type(x))
print(x)
print(type(x[1]))
print(type(x[4]))
print('\n')
print('--------- array ----------\n')
y = np.array(x)
print(type(y))
print(y)
print(type(y[1]))
print(type(y[4]))

--------- lists ----------

<class 'list'>
[1, 2, 3, 4.5, 5.7]
<class 'int'>
<class 'float'>


--------- array ----------

<class 'numpy.ndarray'>
[1.  2.  3.  4.5 5.7]
<class 'numpy.float64'>
<class 'numpy.float64'>


## ndarray

In [7]:
import numpy as np
data1 = [6,7.5,8,0,1]
arr1  = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [8]:
print(arr1.shape)
print(arr1.dtype)

(5,)
float64


In [ ]:
arr1[0] = 7
arr2 = list(arr1)
type(arr2)

In [ ]:
arr2.append(9)
np.array(arr2)

In [9]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print()
print(arr2.ndim)
print()
print(arr2.shape)
print()
print(arr2.dtype)
print()
print(arr2.size)

[[1 2 3 4]
 [5 6 7 8]]

2

(2, 4)

int64

8


In [12]:
data3 = np.zeros(10)
data4 = np.ones(10)
data5 = np.empty([5,3])
print(data3)
print()
print(data4)
print()
print(data5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[0.         0.         0.4472136 ]
 [0.0531494  0.18257419 0.4472136 ]
 [0.2125976  0.36514837 0.4472136 ]
 [0.4783446  0.54772256 0.4472136 ]
 [0.85039041 0.73029674 0.4472136 ]]


In [13]:
data6 = np.arange(15)
print(data6)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [14]:
data7 = np.eye(5)
print(data7)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
print(arr1.dtype)
arr2 = np.array([1, 2], dtype=np.int32)
print(arr2.dtype)

float64
int32


In [16]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int64
float64


In [17]:
arr2 = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr2)
arr2.astype(np.int32)

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]


array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [19]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string)
numeric_strings.astype(float)

AttributeError: module 'numpy' has no attribute 'string'

## Operações entre arrays e escalares

In [20]:
arr3 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr3)
print('Multiplicação: \n',arr3 * arr3)
print('Subtração: \n',arr3 - arr3)

[[1. 2. 3.]
 [4. 5. 6.]]
Multiplicação: 
 [[ 1.  4.  9.]
 [16. 25. 36.]]
Subtração: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
arr3 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr3)
print()
print('Escalar dividindo array: \n',1/arr3)
print()
print('Tirando Raiz quadrada de cada elemento: \n',arr3 ** 0.5)

[[1. 2. 3.]
 [4. 5. 6.]]

Escalar dividindo array: 
 [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]

Tirando Raiz quadrada de cada elemento: 
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


## Indexação e Fatiamento

In [22]:
#arr = [2,14,3,6,8,3,10,222,4]
arr = np.arange(10)
print(arr)
print()
print(arr[5])
print()
print(arr[5:8])
print()
arr[5:8] = 12
print(arr)

[0 1 2 3 4 5 6 7 8 9]

5

[5 6 7]

[ 0  1  2  3  4 12 12 12  8  9]


In [23]:
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[1] = 12345
print(arr_slice)
print(arr)

[12 12 12]
[   12 12345    12]
[    0     1     2     3     4    12 12345    12     8     9]


In [26]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
print()
print(arr2d[2])
print()
print(arr2d[2][2]) #igual a print(arr2d[0, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[7 8 9]

9


In [27]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [28]:
print(arr2d[:2, 1:])
print(arr2d[1, :2])
print(arr2d[:, :1])

[[2 3]
 [5 6]]
[4 5]
[[1]
 [4]
 [7]]


In [29]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])

In [30]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [31]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [32]:
~(names == "Bob")

array([False,  True,  True, False,  True,  True,  True])

In [33]:
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [34]:
mask = (names == "Bob") | (names == "Will")
mask

array([ True, False,  True,  True,  True, False, False])

In [35]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

## TODO

### 1)

Seja um array, A = [10,3,7,5,8,23,15] e dois escalares, x = 6, y = 20. 

Crie uma função que retorne um novo array contendo elementos no intervalo [6,20]

In [43]:
array = np.array([10,3,7,5,8,23,15])
(array  >= 6) | (array  <= 20)

array([ True, False,  True, False,  True,  True,  True])

In [45]:
# Resposta
def filterarray(array, x, y):
    mask = (array  >= x) & (array  <= y)
    return array[mask]

print(filterarray(array, 6, 20))

[10  7  8 15]


## 2)

Escreva um programa usando Numpy que adiciona os valores de um vetor a cada linha de uma matriz. 

Obs: o tamanho do vetor tem de ser o mesmo da quantidade de linhas

vetor = [ 1 1 0]

matriz = [[1 2 3]; [4 5 6]; [7 8 9]]

resultado = [[2 3 3; 5 6 6; 8 9 9]]


Essa função pode ajudar: np.empty_like() 

In [66]:
vetor = np.array([1, 1, 0])
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
for i in range(matriz.shape[0]):
    matriz[i] = matriz[i] + vetor

matriz

array([[2, 3, 3],
       [5, 6, 6],
       [8, 9, 9]])

## Transposição

In [64]:
arr = np.arange(15).reshape((3, 5))
print(arr)
print()
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


## Flattening

In [67]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
print('----- flatten() -----\n')
print(arr2d.flatten())
b1 = arr2d.flatten() 
print(b1)
b1[0] = 100
print(arr2d,'\n')

print('----- ravel() -----\n')
print(arr2d.ravel())
b2 = arr2d.ravel()
print(b2) 
b2[0] = 101
print(arr2d)

----- flatten() -----

[101   2   3   4   5   6   7   8   9]
[101   2   3   4   5   6   7   8   9]
[[101   2   3]
 [  4   5   6]
 [  7   8   9]] 

----- ravel() -----

[101   2   3   4   5   6   7   8   9]
[101   2   3   4   5   6   7   8   9]
[[101   2   3]
 [  4   5   6]
 [  7   8   9]]


## Funções Universais

In [72]:
arr = np.arange(10)
print(arr)
print(np.sqrt(arr)) #raiz quadrada
print()
np.exp(arr) #e^x

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]



array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

## Localização baseada em Condição e Métodos Estatísticos

In [75]:
import numpy as np
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [76]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

[np.float64(1.1),
 np.float64(2.2),
 np.float64(1.3),
 np.float64(1.4),
 np.float64(2.5)]

In [77]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [78]:
arr = np.random.randn(4, 4)
print(arr)
print()
print(np.where(arr > 0, 2, -2)) # atribui 2 p/ x>0, -2 caso contrário
print()
print(np.where(arr > 0, 2, arr)) # atribui 2 p/ x>0, mantém original caso contrário

[[-0.80582933  0.29045669  1.24121174  0.42222695]
 [-0.2367236   0.00912202  0.23730366 -2.60220788]
 [-0.28526182 -0.23984715  0.46842776  0.39284774]
 [ 0.08546106 -0.59993295  0.48818295  1.18687713]]

[[-2  2  2  2]
 [-2  2  2 -2]
 [-2 -2  2  2]
 [ 2 -2  2  2]]

[[-0.80582933  2.          2.          2.        ]
 [-0.2367236   2.          2.         -2.60220788]
 [-0.28526182 -0.23984715  2.          2.        ]
 [ 2.         -0.59993295  2.          2.        ]]


In [79]:
arr = np.random.randn(5, 4)
print(arr)
print()
print(arr.mean()) #ou np.mean(arr)
print()
print(arr.sum())
print()
print(arr.mean(axis=1)) #linhas
print()
print(arr.mean(axis=0)) # colunas

[[ 0.08546616 -1.08150736 -0.65249187 -0.29043531]
 [ 2.03979296  0.44159027  0.52323519  0.47865896]
 [ 0.71093532 -0.95383102 -0.14330456  1.29163252]
 [-0.03106165 -0.25321807 -0.23394714  0.08379799]
 [ 0.77520466  0.69613486  1.63124099 -0.59951536]]

0.22591887674264108

4.518377534852822

[-0.4847421   0.87081935  0.22635806 -0.10860722  0.62576629]

[ 0.71606749 -0.23016626  0.22494652  0.19282776]


 ## Álgebra Linear

In [80]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x)
print()
print(y)
print()
z = np.matmul(x,y) #igual aa np.dot(x,y)
print(z)

[[1. 2. 3.]
 [4. 5. 6.]]

[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]

[[ 28.  64.]
 [ 67. 181.]]


In [82]:
print(x.shape)
print(y.shape)
print(z.shape)

(2, 3)
(3, 2)
(2, 2)


In [83]:
import numpy as np
from numpy.linalg import inv
X = np.random.randn(5, 5)
print(X)
mat = np.matmul(X.T,X) #transposta * X
print()
print(mat)
print()
print(inv(mat)) #inversa

[[-0.44248907 -0.10090429 -0.2041551  -1.05266089 -0.29644342]
 [-0.51814047  0.15270074 -0.14523629  0.63295649 -1.21198432]
 [-1.9140747   0.73209468 -1.13922334 -0.31057207  0.60907501]
 [-1.45876024  0.04411046 -1.94973748 -0.01549715 -0.62262055]
 [-0.57491808  1.99904121  1.52525118  0.54905276  1.24095927]]

[[ 6.58646031 -2.64938683  4.3134528   0.43923496 -0.2118598 ]
 [-2.64938683  4.5675733   2.12743921  1.07239827  2.74400673]
 [ 4.3134528   2.12743921  7.48847009  1.34444753  2.64939328]
 [ 0.43923496  1.07239827  1.34444753  1.90688299  0.04676033]
 [-0.2118598   2.74400673  2.64939328  0.04676033  3.85539331]]

[[ 6.92737065  8.05370549 -5.24065069 -2.38780424 -1.72111921]
 [ 8.05370549  9.86290005 -6.0430691  -3.08263158 -2.3870447 ]
 [-5.24065069 -6.0430691   4.17944953  1.6314456   1.12119473]
 [-2.38780424 -3.08263158  1.6314456   1.63519056  0.92184603]
 [-1.72111921 -2.3870447   1.12119473  0.92184603  1.08207875]]


## Geração de Números Aleatórios

#### Você pode ver todas as distribuições nesse link: [numpy random](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html)

In [84]:
# gera 4 números aleatórios
# entre [0.0,1.0)
samples = np.random.random(4)
samples

array([0.68987524, 0.54898204, 0.06725339, 0.68732438])

In [86]:
# A geração de números é determinística
# Ou seja, é baseada num estado interno
# que chamamos de seed
np.random.seed(42) # set seed
print(np.random.random())
np.random.seed(0) # reset seed
print()
print(np.random.random())

0.3745401188473625

0.5488135039273248


In [88]:
# shuffle reordena um array
# é muito usado antes do processo
# de treino de algoritmo de ML
x = np.arange(10)
print(X)
np.random.shuffle(x)
x

[[-0.44248907 -0.10090429 -0.2041551  -1.05266089 -0.29644342]
 [-0.51814047  0.15270074 -0.14523629  0.63295649 -1.21198432]
 [-1.9140747   0.73209468 -1.13922334 -0.31057207  0.60907501]
 [-1.45876024  0.04411046 -1.94973748 -0.01549715 -0.62262055]
 [-0.57491808  1.99904121  1.52525118  0.54905276  1.24095927]]


array([3, 5, 1, 2, 9, 8, 0, 6, 7, 4])

## Vectorize

In [89]:
import numpy as np

In [90]:
def modulo(x):
    if x % 2 == 1:
        return x**2
    else:
        return x/2
    
print('x = 10 retorna ', modulo(10))
print('x = 11 retorna ', modulo(11))
print('x = [10, 11, 12] retorna ', modulo([10, 11, 12])) # Erro

x = 10 retorna  5.0
x = 11 retorna  121


TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [91]:
modulo_vect = np.vectorize(modulo, otypes=[float])

print('x = [10, 11, 12] retorna ', modulo_vect([10, 11, 12]))
print('x = [[10, 11, 12], [1, 2, 3]] retorna ', modulo_vect([[10, 11, 12], [1, 2, 3]]))

x = [10, 11, 12] retorna  [  5. 121.   6.]
x = [[10, 11, 12], [1, 2, 3]] retorna  [[  5. 121.   6.]
 [  1.   1.   9.]]


## Aplicar uma função – coluna ou linha

In [92]:
#criando matriz
np.random.seed(100)
arr_x = np.random.randint(1,10,size=[4,10])
arr_x

array([[9, 9, 4, 8, 8, 1, 5, 3, 6, 3],
       [3, 3, 2, 1, 9, 5, 1, 7, 3, 5],
       [2, 6, 4, 5, 5, 4, 8, 2, 2, 8],
       [8, 1, 3, 4, 3, 6, 9, 2, 1, 8]])

In [93]:
#função que calcula diferença
def max_minus_min(x):
    return np.max(x) - np.min(x)

# aplicando nas linhas
print('Por linha: ', np.apply_along_axis(max_minus_min, 1, arr=arr_x))

# aplicando nas colunas
print('Por coluna: ', np.apply_along_axis(max_minus_min, 0, arr=arr_x))

Por linha:  [8 8 6 8]
Por coluna:  [7 8 2 7 6 5 8 5 5 5]


In [94]:
vet = np.array([3,6,8,9,11])
np.min(vet)

np.int64(3)

## Outros Métodos

In [97]:
bools = np.array([False, False, True, False])
print(bools.any()) # se houver pelo menos um True
print(bools.all()) # se todos forem True

True
False


In [96]:
arr = np.random.randn(8)
print(arr)
arr.sort() #in-place arr = arr.sort()
print(arr)

[-0.46402358 -0.05702664  0.27592974  1.49451522  0.56682064 -2.30337426
  1.37700072 -1.18738682]
[-2.30337426 -1.18738682 -0.46402358 -0.05702664  0.27592974  0.56682064
  1.37700072  1.49451522]


In [95]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
print(np.unique(ints))

['Bob' 'Joe' 'Will']
[1 2 3 4]


In [99]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.isin(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

## TODO Section

### 3)
Suponha dois arrays, A = [1,4,2,6,5,7,3,0] e B = [3,2,0,9,8,7]. 

Remove de A todo elemento pertencente a B


In [105]:
# resposta
A = np.array([1,4,2,6,5,7,3,0])
B = np.array([3,2,0,9,8,7])

A[~np.isin(A, B)]


array([1, 4, 6, 5])

In [120]:
np.setdiff1d(A,B)

array([1, 4, 5, 6])

### 4)

A célula abaixo faz o download de um dataset e armazena na variável iris_2d. Em seguida, substitui alguns de seus elementos por NaN. Resolva as questões que se seguem:

Dica: analise o método np.isnan [link](https://numpy.org/doc/stable/reference/generated/numpy.isnan.html) para resolver esse exercício.

In [101]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [102]:
iris_2d

array([[5.1, 3.5, 1.4, nan],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, nan, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, nan, 0.2],
       [4.9, 3

a) Encontre o número de NaN na primeira coluna

b) Encontre o número total de NaN

c) Encontre as posições (número da linha) de NaN na primeira coluna

d) Substitua todos os NaN por 0

In [126]:
# Resposta A
sum(np.isnan(iris_2d[:,:1]))

array([4])

In [123]:
np.isnan(iris_2d).sum()

np.int64(20)

In [116]:
# Resposta B
sum(np.isnan(iris_2d.flatten()))

np.int64(20)

In [118]:
#Resposta C
np.where(np.isnan(iris_2d[0]))

(array([3]),)

In [119]:
np.where(np.isnan(iris_2d), 0, iris_2d)

array([[5.1, 3.5, 1.4, 0. ],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 0. , 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 0. , 0.2],
       [4.9, 3